// import React from "react";
// import { View, ScrollView, Text, StyleSheet } from "react-native";
// import BackButton from "../components/BackButton";
// import ScreenWrapper from "../components/ScreenWrapper";

// export default function TermsOfUse() {
//   return (
//     <ScreenWrapper>
//         <BackButton />
//       <ScrollView contentContainerStyle={styles.container}>
//         <Text style={styles.header}>
//           BlinqFix Terms of Use for Customers and Service Pros
//         </Text>
//         <Text style={styles.subHeader}>Effective Date: 05/23/2025</Text>

//         <Text style={styles.sectionTitle}>1. Definitions</Text>
//         <Text style={styles.paragraph}>
//           • "Platform": The BlinqFix website, mobile app, software, and related
//           services.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "User": Any individual or entity accessing the Platform, including
//           Customers and Service Providers.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "Customer": An individual or entity seeking home services through
//           the Platform.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "Service Provider" / "Contractor": Independent professionals
//           providing services via the Platform.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "Services": All repair, maintenance, and related tasks offered and
//           completed through the Platform.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "Content": Text, photos, ratings, reviews, communications, and other
//           data uploaded or generated by Users.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "Booking": A confirmed job request initiated through the Platform.
//         </Text>

//         <Text style={styles.sectionTitle}>2. Overview and Acceptance</Text>
//         <Text style={styles.paragraph}>
//           By accessing or using the Platform, you agree to these Terms, our
//           Privacy Policy, and any additional posted policies. If you do not
//           agree, do not use the Platform.
//         </Text>

//         <Text style={styles.sectionTitle}>
//           3. Account Registration and Eligibility
//         </Text>
//         <Text style={styles.paragraph}>To use the Platform, Users must:</Text>
//         <Text style={styles.paragraph}>
//           • Provide complete and accurate information
//         </Text>
//         <Text style={styles.paragraph}>
//           • Maintain security of login credentials
//         </Text>
//         <Text style={styles.paragraph}>
//           • Be at least 18 years of age and legally able to enter contracts
//         </Text>
//         <Text style={styles.paragraph}>
//           BlinqFix reserves the right to refuse access or cancel accounts at its
//           sole discretion.
//         </Text>

//         <Text style={styles.sectionTitle}>
//           4. Independent Contractor Status
//         </Text>
//         <Text style={styles.paragraph}>
//           Service Providers are independent contractors, not employees,
//           partners, or agents of BlinqFix. They are solely responsible for:
//         </Text>
//         <Text style={styles.paragraph}>• Setting their own schedules</Text>
//         <Text style={styles.paragraph}>• Paying all applicable taxes</Text>
//         <Text style={styles.paragraph}>
//           • Providing their own tools and equipment
//         </Text>
//         <Text style={styles.paragraph}>
//           • Maintaining required licenses and insurance
//         </Text>

//         <Text style={styles.sectionTitle}>5. Scope of Services</Text>
//         <Text style={styles.paragraph}>Customers agree to:</Text>
//         <Text style={styles.paragraph}>• Submit accurate service requests</Text>
//         <Text style={styles.paragraph}>
//           • Treat Service Providers respectfully
//         </Text>
//         <Text style={styles.paragraph}>
//           • Pay for services in a timely manner
//         </Text>
//         <Text style={styles.paragraph}>Service Providers agree to:</Text>
//         <Text style={styles.paragraph}>• Follow in-app job protocols</Text>
//         <Text style={styles.paragraph}>
//           • Communicate clearly with Customers
//         </Text>
//         <Text style={styles.paragraph}>• Submit required documentation</Text>
//         <Text style={styles.paragraph}>• Clean work areas post-service</Text>

//         <Text style={styles.sectionTitle}>
//           ... (continued for remaining sections) ...
//         </Text>
//       </ScrollView>
//     </ScreenWrapper>
//   );
// }

// const styles = StyleSheet.create({
//   container: {
//     padding: 20,
//     backgroundColor: "#fff",
//     marginVertical: -100,
//   },
//   header: {
//     fontSize: 22,
//     fontWeight: "bold",
//     textAlign: "center",
//     marginBottom: 12,
//     marginTop: 120,
//   },
//   subHeader: {
//     fontSize: 14,
//     textAlign: "center",
//     marginBottom: 20,
//     color: "gray",
//   },
//   sectionTitle: {
//     fontSize: 18,
//     fontWeight: "600",
//     marginTop: 20,
//     marginBottom: 8,
//   },
//   paragraph: {
//     fontSize: 14,
//     marginBottom: 6,
//     lineHeight: 20,
//   },
// });

import React from "react";
import { View, ScrollView, Text, StyleSheet, SafeAreaView, TouchableOpacity } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import {
  ArrowLeft,
  FileText,
  BookText,
  CheckSquare,
  User,
  Briefcase,
  Wrench,
} from "lucide-react-native";
import { useNavigation } from "@react-navigation/native";

const Section = ({ title, icon: Icon, children }) => (
  <View style={styles.sectionContainer}>
    <View style={styles.sectionHeader}>
      <Icon color="#60a5fa" size={24} style={styles.sectionIcon} />
      <Text style={styles.sectionTitle}>{title}</Text>
    </View>
    <View style={styles.sectionContent}>{children}</View>
  </View>
);

const Paragraph = ({ children, isListItem = false }) => (
  <Text style={[styles.paragraph, isListItem && styles.listItem]}>
    {isListItem && "• "}
    {children}
  </Text>
);

export default function TermsOfUse() {
  const navigation = useNavigation();

  return (
    <LinearGradient colors={['#0f172a', '#1e3a8a', '#312e81']} style={styles.container}>
      <SafeAreaView style={{ flex: 1 }}>
        <ScrollView contentContainerStyle={styles.scrollContent}>
          {/* Header */}
          <View style={styles.header}>
            <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
              <ArrowLeft color="#fff" size={24} />
            </TouchableOpacity>
            <View style={styles.headerCenter}>
              <View style={styles.headerBadge}>
                <FileText color="#e0e7ff" size={16} />
                <Text style={styles.headerBadgeText}>Legal</Text>
              </View>
              <Text style={styles.headerTitle}>Terms of Use</Text>
            </View>
            <View style={{ width: 40 }} />
          </View>

          {/* Intro Card */}
          <View style={styles.introCard}>
            <LinearGradient
              colors={['rgba(255,255,255,0.05)', 'rgba(255,255,255,0.02)']}
              style={styles.introGradient}
            >
              <Text style={styles.introTitle}>BlinqFix Terms of Use for Customers and Service Pros</Text>
              <Text style={styles.subHeader}>Effective Date: 05/23/2025</Text>
            </LinearGradient>
          </View>
          
          <Section title="1. Definitions" icon={BookText}>
            <Paragraph isListItem>"Platform": The BlinqFix website, mobile app, software, and related services.</Paragraph>
            <Paragraph isListItem>"User": Any individual or entity accessing the Platform, including Customers and Service Providers.</Paragraph>
            <Paragraph isListItem>"Customer": An individual or entity seeking home services through the Platform.</Paragraph>
            <Paragraph isListItem>"Service Provider" / "Contractor": Independent professionals providing services via the Platform.</Paragraph>
            <Paragraph isListItem>"Services": All repair, maintenance, and related tasks offered and completed through the Platform.</Paragraph>
            <Paragraph isListItem>"Content": Text, photos, ratings, reviews, communications, and other data uploaded or generated by Users.</Paragraph>
            <Paragraph isListItem>"Booking": A confirmed job request initiated through the Platform.</Paragraph>
          </Section>

          <Section title="2. Overview and Acceptance" icon={CheckSquare}>
            <Paragraph>By accessing or using the Platform, you agree to these Terms, our Privacy Policy, and any additional posted policies. If you do not agree, do not use the Platform.</Paragraph>
          </Section>

          <Section title="3. Account Registration and Eligibility" icon={User}>
            <Paragraph>To use the Platform, Users must:</Paragraph>
            <Paragraph isListItem>Provide complete and accurate information</Paragraph>
            <Paragraph isListItem>Maintain security of login credentials</Paragraph>
            <Paragraph isListItem>Be at least 18 years of age and legally able to enter contracts</Paragraph>
            <Paragraph>BlinqFix reserves the right to refuse access or cancel accounts at its sole discretion.</Paragraph>
          </Section>

          <Section title="4. Independent Contractor Status" icon={Briefcase}>
            <Paragraph>Service Providers are independent contractors, not employees, partners, or agents of BlinqFix. They are solely responsible for:</Paragraph>
            <Paragraph isListItem>Setting their own schedules</Paragraph>
            <Paragraph isListItem>Paying all applicable taxes</Paragraph>
            <Paragraph isListItem>Providing their own tools and equipment</Paragraph>
            <Paragraph isListItem>Maintaining required licenses and insurance</Paragraph>
          </Section>

          <Section title="5. Scope of Services" icon={Wrench}>
            <Paragraph>Customers agree to:</Paragraph>
            <Paragraph isListItem>Submit accurate service requests</Paragraph>
            <Paragraph isListItem>Treat Service Providers respectfully</Paragraph>
            <Paragraph isListItem>Pay for services in a timely manner</Paragraph>
            <Paragraph>Service Providers agree to:</Paragraph>
            <Paragraph isListItem>Follow in-app job protocols</Paragraph>
            <Paragraph isListItem>Communicate clearly with Customers</Paragraph>
            <Paragraph isListItem>Submit required documentation</Paragraph>
            <Paragraph isListItem>Clean work areas post-service</Paragraph>
          </Section>
          
          <Text style={styles.continuedText}>... (continued for remaining sections) ...</Text>

        </ScrollView>
      </SafeAreaView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
    marginTop: 40,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 20,
  },
  backButton: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    padding: 10,
    borderRadius: 99,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center'
  },
  headerCenter: {
    alignItems: 'center',
    flex: 1
  },
  headerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginBottom: 8
  },
  headerBadgeText: {
    color: '#fff',
    marginLeft: 6,
    fontSize: 12,
    fontWeight: '500'
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff'
  },
  introCard: {
    marginBottom: 24,
    borderRadius: 16,
    overflow: 'hidden'
  },
  introGradient: {
    padding: 20
  },
  introTitle: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
    color: '#fff'
  },
  subHeader: {
    fontSize: 14,
    textAlign: "center",
    color: "#94a3b8",
  },
  sectionContainer: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    marginBottom: 20,
    padding: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)'
  },
  sectionIcon: {
    marginRight: 12
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    flex: 1
  },
  sectionContent: {
    // No specific styles needed here, children will be paragraphs
  },
  paragraph: {
    fontSize: 15,
    marginBottom: 10,
    lineHeight: 22,
    color: '#e0e7ff',
  },
  listItem: {
    paddingLeft: 4,
  },
  continuedText: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
    fontStyle: 'italic',
    marginTop: 16
  }
});