// import React from "react";
// import { View, ScrollView, Text, StyleSheet } from "react-native";
// import BackButton from "../components/BackButton";
// import ScreenWrapper from "../components/ScreenWrapper";

// export default function TermsOfUse() {
//   return (
//     <ScreenWrapper>
//         <BackButton />
//       <ScrollView contentContainerStyle={styles.container}>
//         <Text style={styles.header}>
//           BlinqFix Terms of Use for Customers and Service Pros
//         </Text>
//         <Text style={styles.subHeader}>Effective Date: 05/23/2025</Text>

//         <Text style={styles.sectionTitle}>1. Definitions</Text>
//         <Text style={styles.paragraph}>
//           • "Platform": The BlinqFix website, mobile app, software, and related
//           services.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "User": Any individual or entity accessing the Platform, including
//           Customers and Service Providers.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "Customer": An individual or entity seeking home services through
//           the Platform.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "Service Provider" / "Contractor": Independent professionals
//           providing services via the Platform.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "Services": All repair, maintenance, and related tasks offered and
//           completed through the Platform.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "Content": Text, photos, ratings, reviews, communications, and other
//           data uploaded or generated by Users.
//         </Text>
//         <Text style={styles.paragraph}>
//           • "Booking": A confirmed job request initiated through the Platform.
//         </Text>

//         <Text style={styles.sectionTitle}>2. Overview and Acceptance</Text>
//         <Text style={styles.paragraph}>
//           By accessing or using the Platform, you agree to these Terms, our
//           Privacy Policy, and any additional posted policies. If you do not
//           agree, do not use the Platform.
//         </Text>

//         <Text style={styles.sectionTitle}>
//           3. Account Registration and Eligibility
//         </Text>
//         <Text style={styles.paragraph}>To use the Platform, Users must:</Text>
//         <Text style={styles.paragraph}>
//           • Provide complete and accurate information
//         </Text>
//         <Text style={styles.paragraph}>
//           • Maintain security of login credentials
//         </Text>
//         <Text style={styles.paragraph}>
//           • Be at least 18 years of age and legally able to enter contracts
//         </Text>
//         <Text style={styles.paragraph}>
//           BlinqFix reserves the right to refuse access or cancel accounts at its
//           sole discretion.
//         </Text>

//         <Text style={styles.sectionTitle}>
//           4. Independent Contractor Status
//         </Text>
//         <Text style={styles.paragraph}>
//           Service Providers are independent contractors, not employees,
//           partners, or agents of BlinqFix. They are solely responsible for:
//         </Text>
//         <Text style={styles.paragraph}>• Setting their own schedules</Text>
//         <Text style={styles.paragraph}>• Paying all applicable taxes</Text>
//         <Text style={styles.paragraph}>
//           • Providing their own tools and equipment
//         </Text>
//         <Text style={styles.paragraph}>
//           • Maintaining required licenses and insurance
//         </Text>

//         <Text style={styles.sectionTitle}>5. Scope of Services</Text>
//         <Text style={styles.paragraph}>Customers agree to:</Text>
//         <Text style={styles.paragraph}>• Submit accurate service requests</Text>
//         <Text style={styles.paragraph}>
//           • Treat Service Providers respectfully
//         </Text>
//         <Text style={styles.paragraph}>
//           • Pay for services in a timely manner
//         </Text>
//         <Text style={styles.paragraph}>Service Providers agree to:</Text>
//         <Text style={styles.paragraph}>• Follow in-app job protocols</Text>
//         <Text style={styles.paragraph}>
//           • Communicate clearly with Customers
//         </Text>
//         <Text style={styles.paragraph}>• Submit required documentation</Text>
//         <Text style={styles.paragraph}>• Clean work areas post-service</Text>

//         <Text style={styles.sectionTitle}>
//           ... (continued for remaining sections) ...
//         </Text>
//       </ScrollView>
//     </ScreenWrapper>
//   );
// }

// const styles = StyleSheet.create({
//   container: {
//     padding: 20,
//     backgroundColor: "#fff",
//     marginVertical: -100,
//   },
//   header: {
//     fontSize: 22,
//     fontWeight: "bold",
//     textAlign: "center",
//     marginBottom: 12,
//     marginTop: 120,
//   },
//   subHeader: {
//     fontSize: 14,
//     textAlign: "center",
//     marginBottom: 20,
//     color: "gray",
//   },
//   sectionTitle: {
//     fontSize: 18,
//     fontWeight: "600",
//     marginTop: 20,
//     marginBottom: 8,
//   },
//   paragraph: {
//     fontSize: 14,
//     marginBottom: 6,
//     lineHeight: 20,
//   },
// });

//latest working


import React from "react";
import { View, ScrollView, Text, StyleSheet, SafeAreaView, TouchableOpacity } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { ArrowLeft, FileText } from "lucide-react-native";
import { useNavigation } from "@react-navigation/native";

const Section = ({ title, children }) => (
  <View style={styles.sectionContainer}>
    <Text style={styles.sectionTitle}>{title}</Text>
    <View style={styles.sectionContent}>{children}</View>
  </View>
);

const Paragraph = ({ children, isListItem = false }) => (
  <Text style={[styles.paragraph, isListItem && styles.listItem]}>
    {isListItem && "• "}
    {children}
  </Text>
);

export default function TermsOfUse() {
  const navigation = useNavigation();

  return (
    <LinearGradient colors={["#0f172a", "#1e3a8a", "#312e81"]} style={styles.container}>
      <SafeAreaView style={{ flex: 1 }}>
        <ScrollView contentContainerStyle={styles.scrollContent}>
          {/* Header */}
          <View style={styles.header}>
            <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
              <ArrowLeft color="#fff" size={24} />
            </TouchableOpacity>
            <View style={styles.headerCenter}>
              <View style={styles.headerBadge}>
                <FileText color="#e0e7ff" size={16} />
                <Text style={styles.headerBadgeText}>Legal</Text>
              </View>
              <Text style={styles.headerTitle}>Terms of Use</Text>
            </View>
            <View style={{ width: 40 }} />
          </View>

          {/* Intro Card */}
          <View style={styles.introCard}>
            <LinearGradient
              colors={["rgba(255,255,255,0.05)", "rgba(255,255,255,0.02)"]}
              style={styles.introGradient}
            >
              <Text style={styles.introTitle}>Terms of Use — BlinqFix</Text>
              <Text style={styles.subHeader}>Last Updated: May 5, 2025</Text>
            </LinearGradient>
          </View>

          <Section title="Important Notice — Arbitration & Class Action Waiver">
            <Paragraph>
              THIS AGREEMENT CONTAINS A BINDING ARBITRATION PROVISION AND A CLASS ACTION WAIVER... PLEASE READ CAREFULLY.
            </Paragraph>
          </Section>

          <Section title="Acceptance of These Terms">
            <Paragraph>
              These Terms of Use ("Terms") govern your access to and use of the BlinqFix mobile application, website(s), and related services (collectively, the "Platform").
            </Paragraph>
          </Section>

          <Section title="Identity Verification; Background & Business Credit Checks">
            <Paragraph>
              You authorize BlinqFix to use your information to verify your identity, conduct background checks, and obtain business credit checks, through third-party vendors, in accordance with applicable law.
            </Paragraph>
          </Section>

          <Section title="1) Nature of the Platform">
            <Paragraph>
              BlinqFix is a marketplace connecting Customers with independent Providers. BlinqFix does not perform services and does not employ Providers.
            </Paragraph>
          </Section>

          <Section title="2) Eligibility & Accounts">
            <Paragraph isListItem>You must be at least 18 and legally capable of entering contracts.</Paragraph>
            <Paragraph isListItem>You agree to provide accurate information and keep it current.</Paragraph>
          </Section>

          <Section title="3) Quotes, Pricing & Scope">
            <Paragraph>
              Pricing may be generated by our intake logic and algorithm. A booking is finalized when a Provider accepts the job.
            </Paragraph>
          </Section>

          <Section title="4) Payments; Holds; Fees">
            <Paragraph>
              Payments are processed through our third-party processor and may be held in escrow. Providers receive payment net of BlinqFix service fees.
            </Paragraph>
          </Section>

          <Section title="5) Cancellations & Refunds">
            <Paragraph isListItem>Before Provider acceptance: cancel at no charge.</Paragraph>
            <Paragraph isListItem>After acceptance / in-progress: cancellation or no-show fees may apply.</Paragraph>
            <Paragraph isListItem>Refunds: At BlinqFix’s discretion consistent with policy.</Paragraph>
          </Section>

          <Section title="6) Provider Obligations">
            <Paragraph isListItem>Maintain all required licenses, permits, and insurance.</Paragraph>
            <Paragraph isListItem>Perform services professionally and safely.</Paragraph>
          </Section>

          <Section title="7) Customer Obligations">
            <Paragraph isListItem>Provide accurate job details and safe access.</Paragraph>
            <Paragraph isListItem>Ensure timely payment.</Paragraph>
          </Section>

          <Section title="8) Communications; Consent to SMS/Calls/Push">
            <Paragraph>
              You may receive transactional and (if opted in) marketing messages. Message/data rates may apply.
            </Paragraph>
          </Section>

          <Section title="9) Reviews & Content">
            <Paragraph>
              If you post reviews or content, you grant BlinqFix a license to use it. You are responsible for ensuring it does not infringe rights or laws.
            </Paragraph>
          </Section>

          <Section title="10) Prohibited Conduct">
            <Paragraph>
              You agree not to misuse the Platform, circumvent fees, or violate laws.
            </Paragraph>
          </Section>

          <Section title="11) Disclaimers">
            <Paragraph>
              THE PLATFORM IS PROVIDED "AS IS". BLINQFIX MAKES NO WARRANTIES.
            </Paragraph>
          </Section>

          <Section title="12) Limitation of Liability">
            <Paragraph>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, BLINQFIX WILL NOT BE LIABLE FOR INDIRECT OR CONSEQUENTIAL DAMAGES. LIABILITY IS CAPPED AT $500 OR JOB VALUE.
            </Paragraph>
          </Section>

          <Section title="13) Indemnification">
            <Paragraph>
              You agree to indemnify and hold harmless BlinqFix against claims related to your use of the Platform.
            </Paragraph>
          </Section>

          <Section title="14) Dispute Resolution — Binding Arbitration; Class Waiver">
            <Paragraph>
              Except where prohibited by law, disputes will be resolved by binding arbitration in Miami-Dade County, Florida.
            </Paragraph>
          </Section>

          <Section title="15) Privacy">
            <Paragraph>
              Your use of the Platform is governed by our Privacy Policy.
            </Paragraph>
          </Section>

          <Section title="16) Suspension & Termination">
            <Paragraph>
              We may suspend or terminate access for violations or safety risks. You may close your account at any time.
            </Paragraph>
          </Section>

          <Section title="17) Changes to the Platform or Terms">
            <Paragraph>
              We may modify these Terms at any time. Continued use constitutes acceptance.
            </Paragraph>
          </Section>

          <Section title="18) Subscriptions">
            <Paragraph>
              Subscription Services may auto-renew. You can opt out or cancel anytime.
            </Paragraph>
          </Section>

          <Section title="19) Marketplace Payments">
            <Paragraph>
              Payments are processed via Stripe. Providers must agree to Stripe terms. Customers authorize charges.
            </Paragraph>
          </Section>

          <Section title="20) Disputes Between or Among Users">
            <Paragraph>
              BlinqFix may offer dispute resolution tools, but is not obligated to intervene.
            </Paragraph>
          </Section>

          <Section title="21) Miscellaneous">
            <Paragraph isListItem>Independent Contractors: Providers are not employees.</Paragraph>
            <Paragraph isListItem>Assignment: You may not assign without consent.</Paragraph>
            <Paragraph isListItem>Contact: support@blinqfix.com</Paragraph>
          </Section>
        </ScrollView>
      </SafeAreaView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { padding: 20, paddingBottom: 40, marginTop: 40 },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingBottom: 20 },
  backButton: { backgroundColor: "rgba(255,255,255,0.1)", padding: 10, borderRadius: 99, width: 44, height: 44, justifyContent: "center", alignItems: "center" },
  headerCenter: { alignItems: "center", flex: 1 },
  headerBadge: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(255,255,255,0.1)", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, marginBottom: 8 },
  headerBadgeText: { color: "#fff", marginLeft: 6, fontSize: 12, fontWeight: "500" },
  headerTitle: { fontSize: 24, fontWeight: "bold", color: "#fff" },
  introCard: { marginBottom: 24, borderRadius: 16, overflow: "hidden" },
  introGradient: { padding: 20 },
  introTitle: { fontSize: 20, fontWeight: "bold", textAlign: "center", marginBottom: 8, color: "#fff" },
  subHeader: { fontSize: 14, textAlign: "center", color: "#94a3b8" },
  sectionContainer: { backgroundColor: "rgba(255,255,255,0.05)", borderRadius: 16, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", marginBottom: 20, padding: 20 },
  sectionTitle: { fontSize: 18, fontWeight: "bold", color: "#fff", marginBottom: 12 },
  paragraph: { fontSize: 15, marginBottom: 10, lineHeight: 22, color: "#e0e7ff" },
  listItem: { paddingLeft: 4 },
});
